### ISSUE TITLE
Support for middleware?

### ISSUE THREAD

**Issue by prsolucoes** [oatpp/oatpp#194]
Hi,

It has support for middleware?

Example in other framework:
https://github.com/ipkn/crow/wiki/Middleware
or
https://www.alexedwards.net/blog/making-and-using-middleware

Thanks.

**Comment by bhorn** [comment]
Hi there,

in general, oatpp has some nice features that make your life easy and may be seen as Middleware-Features.

1) Dependency-Injection
2) Request- and Response-Interceptors (I.E. for gzipping or other common tasks)
3) Nearly everything is customisable by providing your own implementations.

Further, you can create your own subclass of the Api-Controller and use this subclass with all commonly needed functionalities. 

Do you have anything particular in mind we can help you with?

**Comment by lganzzzo** [comment]
Hey,

Just to add a few details to @bhorn answer:
- You can add multiple `RequestInterceptor`s to the `HttpConnectionHandler` in order to do some pre-checks of the request. See [addRequestInterceptor](https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/HttpConnectionHandler.hpp#L90) method.
- You can set up automatic compression/decompression of the content - see [oatpp-zlib](https://oatpp.io/docs/modules/oatpp-zlib/) module.
- Also, there are convenient features as [CORS support](https://oatpp.io/docs/components/api-controller/#cors) and [Authorization support](https://oatpp.io/docs/components/api-controller/#authorization-basic)

Regards,
Leonid

**Comment by prsolucoes** [comment]
Hi,

Generally in python or go I add middleware for some controllers group that get bearer token (jwt) and decide it can continue or not the request. The middleware can send the user to 403 (not authorized) If detect invalid token.

So for administration controllers group i have  some middleware and for site controllers I have others middleware.

This is possible?

**Comment by lganzzzo** [comment]
Hello, 
Yes you are correct, it is possible.
Please find authorization bearer example code snippets. https://oatpp.io/docs/components/api-controller/#authorization-bearer

Regards,
Leonid

**Comment by prsolucoes** [comment]
Ok,

I will test now.

Thanks.

**Comment by lganzzzo** [comment]
I am closing this issue.
@prsolucoes please feel free to reopen in case you have more questions on this matter.

Regards,
Leonid
