### ISSUE TITLE
How can I async multiple upload file?

### ISSUE THREAD

**Issue by codderembedded** [oatpp/oatpp#202]
I have tryed Async Complete Example. But I dont understand Endpoint_Async. How can I select multiple file and How can I save?

![image](https://user-images.githubusercontent.com/49305144/76069008-4333d600-5fa3-11ea-9ffc-4b0f7eb7e63a.png)

**Comment by lganzzzo** [comment]
Hello @codderembedded ,

*I am posting an answer from the Gitter chat here*

For the detailed description of how-to upload Multipart data using oatpp Async API please
see [Async multipart upload](https://oatpp.io/docs/features/upload-file/#async-api-multipart-upload)

Please also note that at the moment the proper multipart Swagger-UI annotations are not implemented.
In order to test the upload use the following curl command:
```bash
curl http://localhost:8000/test/multipart-all -F part1=@001.txt -F part2=@002.txt -H "Expect: "
```

Regards,
Leonid
