### ISSUE TITLE
oatpp::Boolean type toString methods cannot serialize 'false' value

### ISSUE THREAD

**Issue by NickPak** [oatpp/oatpp#275]
When I declared a `Boolean` argument using the `QUERY` macro and tried to pass the `false` value, it caused a crash：
```
oatpp::base::StrBuffer::getSize // StrBuffer.cpp:140 << Crash here
oatpp::data::stream::WriteCallback::writeSimple //Stream.hpp:242
oatpp::web::client::ApiClient::addPathQueryParams //ApiClient.cpp:103
oatPP::web::client::ApiClient::formatPath //ApiClient.cpp:123
oatpp::web::client::ApiClient::executeRequest //ApiClient.cpp:170
......
```
 I've tried to fix it, and it was due to the `toString` method returned a `nullptr`.
#274

**Comment by bamkrs** [comment]
So the main issue is that your value to your key is nullptr. This might be a expected behaviour since some URL parameter are only the key itself: `https://foo.bar/baz?key`

So the real solution would be to add a Safecheck in `addPathQueryParams` like:

https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/client/ApiClient.cpp#L95
```c++
 void ApiClient::addPathQueryParams(data::stream::ConsistentOutputStream* stream,
                                   const std::shared_ptr<StringToStringMap>& params) {
  
  auto curr = params->getFirstEntry();
  if(curr != nullptr) {
    stream->writeSimple("?", 1);
    stream->writeSimple(curr->getKey());
    if (curr->getValue().get() != nullptr) {
      stream->writeSimple("=", 1);
      stream->writeSimple(curr->getValue());
    }
    curr = curr->getNext();
    while (curr != nullptr) {
      stream->writeSimple("&", 1);
      stream->writeSimple(curr->getKey());
      if (curr->getValue().get() != nullptr) {
        stream->writeSimple("=", 1);
        stream->writeSimple(curr->getValue());
      }
      curr = curr->getNext();
    }
  }
  
}
```

Another additional problem that has to be addressed is the issue that `writeSimple(oatpp::String)` crashes when an empty string is passed. This must be solved, too!

https://github.com/oatpp/oatpp/blob/master/src/oatpp/core/data/stream/Stream.hpp#L241
```c++
v_io_size writeSimple(const oatpp::String& str){
    if (str.get() != nullptr) {
        return writeSimple(str->getData(), str->getSize());
    }
    return 0;
}
```

But we should check back to @lganzzzo for his opinion.

**Comment by lganzzzo** [comment]
Hey guys,

Please find the review and the [comment](https://github.com/oatpp/oatpp/pull/274#issuecomment-658173567) in #274 

> So the main issue is that your value to your key is nullptr. This might be a expected behaviour since some URL parameter are only the key itself: [https://foo.bar/baz?key=]
>
> So the real solution would be to add a Safecheck in addPathQueryParams like:

I think it's a good note. However, I believe it's a separate issue.
So let's create a separate issue for it.

> Another additional problem that has to be addressed is the issue that writeSimple(oatpp::String) crashes when an empty string is passed. This must be solved, too!

Good note too. And a different issue too (as for me).
Remark: It crashes on a `nullptr` string. In oatpp the `nullptr` string and an `empty string ("")` are different values.
