### ISSUE TITLE
API question - ErrorHandler

### ISSUE THREAD

**Issue by natanael** [oatpp/oatpp#277]
In file: oatpp/web/server/handler/ErrorHandler.hpp

About the method:
```cpp
namespace oatpp { namespace web { namespace server { namespace handler {
class ErrorHandler {
// [...]
  std::shared_ptr<protocol::http::outgoing::Response> handleError(const protocol::http::Status& status, const oatpp::String& message);
};
```
# Question

While implementing an ErrorHandler I noticed the error is not provided to `handleError` but only it's message `error->what()`
as defined in:
```cpp
class ApiController : public oatpp::base::Countable {
// [...]
  template<class T>
  class Handler : public RequestHandler {
     async::Action handleError(async::Error* error) override {
        auto response = m_handler->m_controller->m_errorHandler->handleError(protocol::http::Status::CODE_500, error->what());
        return this->_return(response);
      }
    };
// [...]
public:
  std::shared_ptr<OutgoingResponse> handle(const std::shared_ptr<IncomingRequest>& request) override {
      if(m_method == nullptr) {
        if(m_methodAsync == nullptr) {
          return m_controller->handleError(Status::CODE_500, "[ApiController]: Error. Handler method is nullptr.");
        }
        return m_controller->handleError(Status::CODE_500, "[ApiController]: Error. Non-async call to async endpoint.");
      }
      if(m_controller->m_errorHandler) {
        try {
          return (m_controller->*m_method)(request);
        } catch (oatpp::web::protocol::http::HttpError& error) {
          return m_controller->m_errorHandler->handleError(error.getInfo().status, error.getMessage(), error.getHeaders());
        } catch (std::exception& error) {
          return m_controller->m_errorHandler->handleError(protocol::http::Status::CODE_500, error.what());
        } catch (...) {
          return m_controller->m_errorHandler->handleError(protocol::http::Status::CODE_500, "Unknown error");
        }
      }
      return (m_controller->*m_method)(request);
    }
// [...]
}
```
What would be the correct way to identify which error actually occurred then? Do a string match on the message? Use something other than the ErrorHandler?

My actual scenario is about the DTO validation failing with messages such as `[oatpp::parser::json::mapping::Deserializer::deserializeEnum()]: Error. Can't deserialize Enum.` in a request with hundreds of fields. I would like to identify which one failed. We assumed it would be possible to get the field name from the `oatpp::parser::ParsingError`, which does not seem possible today but could be by changing:
```cpp
namespace oatpp { namespace data { namespace mapping {
/**
 * Abstract ObjectMapper class.
 */
class ObjectMapper {
/// [...]
 template<class Wrapper>
  Wrapper readFromString(const oatpp::String& str) const {
    auto type = Wrapper::Class::getType();
    oatpp::parser::Caret caret(str);
    auto result = read(caret, type).template staticCast<Wrapper>();
    if(!result) {
      throw oatpp::parser::ParsingError( // <-- If we give it the label somehow
                                        caret.getErrorMessage(), 
                                        caret.getErrorCode(), 
                                        caret.getPosition());
    }
    return result;
  }
// [...]
}
```

**Comment by lganzzzo** [comment]
Hey @natanael ,

Currently, this functionality is pretty limited and needs to be improved.
What I was thinking of - is to enhance the `oatpp::parser::Caret` to be able to store a parsing trace in case of error.
So that if an error occurs in the huge DTO it could provide the whole parsing path to the error-place.

Also as you correctly pointed - it's a good idea to pass not just the error message but probably the whole error object to the `ErrorHandler::handleError()` method.

## Temporary workaround

As a temporary workaround, you can do parsing manually instead of using `BODY_DTO` request mapping:

```cpp
ENDPOINT("POST", "/path", postBody, 
         REQUEST(std::shared_ptr<IncomingRequest>, request))
{
   try {
    auto bodyDto = request->readBodyToDto<oatpp::Object<MyDto>>(getDefaultObjectMapper().get());
  } catch (const oatpp::parser::ParsingError& e) {
    OATPP_LOGD("Error", "Position=%d", e.getPosition()); //<--- get byte position of the error in the parsed data.
  }
  ...
}
```

**Comment by JeremyGuinn** [comment]
@lganzzzo I can work on getting up a PR to close the error handler part of this and issue 521. This shouldn't be too complicated of a change. 

I'm not sure how advanced you wanted to get with it, but otherwise I'll probably just add a new backwards compatible virtual method to pass the std::exception to and the user can dynamic_cast to a specific error for special handling if needed.

Let me know if you have any specific design considerations I should keep in mind.

**Comment by lganzzzo** [comment]
Hey @JeremyGuinn , please don't hesitate to create PRs.

> I'm not sure how advanced you wanted to get with it, but otherwise I'll probably just add a new backwards compatible virtual method to pass the std::exception to and the user can dynamic_cast to a specific error for special handling if needed.

Sounds good.
Personally I like the idea of a Controller-specific error handler. Something like the following:

```cpp
class MyController : public ... {
public:

  <ENDPOINTS>

   OutgoingRequest handleError(std::exception e) override {
     // TODO dynamic casts
   }

};
```

I think this method can be called from here - https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/api/ApiController.hpp#L274

However, you might have better ideas.

Regards,
Leonid

**Comment by JeremyGuinn** [comment]
@lganzzzo,

I noticed a couple public methods already defined on ApiController that have [under discussion]. However, I couldn't find any of that discussion on github. Now seems like an apt time to revisit the discussion.

```c++
/**
 * [under discussion]
 * Set error handler to handle calls to handleError
 */
void setErrorHandler(const std::shared_ptr<handler::ErrorHandler>& errorHandler);

/**
 * [under discussion]
 * Do not use it directly. This method is under discussion.
 * Currently returns Response created by registered ErrorHandler or returns Response created by DefaultErrorHandler::handleDefaultError
 * Notice: Does not throw the Error anymore, error-response has to be returned by the caller!
 */
std::shared_ptr<OutgoingResponse> handleError(const Status& status, const oatpp::String& message) const;
```

**Comment by lganzzzo** [comment]
Hey @JeremyGuinn ,

Good point.

Those methods are currently used in a bit awkward way in my opinion.

```cpp
std::shared_ptr<OutgoingResponse> handleError(const Status& status, const oatpp::String& message) const;
```

The signature of this method looks more like a `sendErrorMessage` method and is used this exact way at the moment. It doesn't actually handle errors.

So my proposition would be the following:

- Change `handleError` to the following:
   ```cpp
   std::shared_ptr<OutgoingResponse> handleError(std::exception_ptr e) const;
   ```
   Now it's ready to handle errors ...

- Change this block - https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/api/ApiController.hpp#L274
   to actually direct `std::current_exception` to `handleError` method.


The open questions are:
- What should be the default behavior of `handleError` method - My guess is that it should just return `500` with basic information. I don't want it to rethrow by default (which also makes sense - handing error to global errorHandler) - not to have chains of throw - catch - throw - catch - I just don't like it, and it will affect the performance.
- What to do with `void setErrorHandler(const std::shared_ptr<handler::ErrorHandler>& errorHandler);` method?
Do we need it, why don't we just make `handleError` virtual and let the user override its behavior instead of setting some redundant error handler to the controller.
- We should also probably change interface of `ErrorHandler` too https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/handler/ErrorHandler.hpp#L56 to something like this
   ```cpp
   virtual std::shared_ptr<OutgoingResponse> handleError(std::exception_ptr e) = 0;
   ```
To be the same as `Controller::handleError`.

Please let me know what's your opinion.

**Comment by JeremyGuinn** [comment]
virtual std::shared_ptr<OutgoingResponse> handleError(std::exception_ptr e) = 0;


I was thinking of keeping the `void setErrorHandler(const std::shared_ptr<handler::ErrorHandler>& errorHandler);`, only because error handler logic may be shared across controllers, but the logic may not be general enough to live in the ConnectionHandler's root error handler. It's a similar premise and would be consistent to the `setDefaultAuthorizationHandler` and `handleDefaultAuthorization` methods.

Shouldn't it be the case that if the controller does not handle the exception, that the exception is given to the root exception handler? I'm not sure how we would achieve that without a rethrow.

**Comment by lganzzzo** [comment]
Hey @JeremyGuinn ,

> Shouldn't it be the case that if the controller does not handle the exception, that the exception is given to the root exception handler? I'm not sure how we would achieve that without a rethrow.

Let us do the following:
- let's use `std::exception_ptr` so that we are able to rethrow.
- if the error handler is set via `setErrorHandler` - we catch and hand exception_ptr to the error handler
- if the error handler isn't set - we don't catch - and it'll go to the global handler
