### ISSUE TITLE
Stopping server in a clear way - how to do it?

### ISSUE THREAD

**Issue by nicraMarcin** [oatpp/oatpp#280]
Hello,
I have issue about clean stopping server.
According to starter project 
```cpp
void run() {

  // other stuff

  /* Create server which takes provided TCP connections and passes them to HTTP connection handler */
  oatpp::network::server::Server server(connectionProvider, connectionHandler);

  /* Priny info about server port */
  OATPP_LOGI("MyApp", "Server running on port %s", connectionProvider->getProperty("port").getData());

  /* Run server */
  server.run();
  
}

int main(int argc, const char * argv[]) {

  oatpp::base::Environment::init();

  run();

  /* Print how much objects were created during app running, and what have left-probably leaked */
  /* Disable object counting for release builds using '-D OATPP_DISABLE_ENV_OBJECT_COUNTERS' flag for better performance */
  std::cout << "\nEnvironment:\n";
  std::cout << "objectsCount = " << oatpp::base::Environment::getObjectsCount() << "\n";
  std::cout << "objectsCreated = " << oatpp::base::Environment::getObjectsCreated() << "\n\n";

  oatpp::base::Environment::destroy();

  return 0;
}
```

`run()` function is blocking function because of while loop in Sever object `while(getStatus() == STATUS_RUNNING)`. This is getting status but we cannot change thist status during loop.

According above example ` oatpp::base::Environment::destroy();` this will never be executed.

My fragment of code
```cpp
run(oatpp::base::CommandLineArguments(argc, argv));

  std::cout << "This should be printed after run() is ended" << std::endl;
```
Now I run this and stop with two ways:
- ctrl+c

> $ ./nmsapi 
NMS:NmsComponent - Loading configuration from /etc/nms/nms.config.json
NMS:UserCache - Creating UserCache
NMS:UserCache - Cache size 0, current timestamp: 1595409776
NMS:NMS - Server running on port 8888
^C

- and `kill` process

> $ ./nmsapi 
NMS:NmsComponent - Loading configuration from /etc/nms/nms.config.json
NMS:UserCache - Creating UserCache
NMS:UserCache - Cache size 0, current timestamp: 1595409782
NMS:NMS - Server running on port 8888
Done

We can see that `std::cout` is not executed in both cases.
_oatpp::network::server::Server_ has method `stop() `but we cannot execute it because `run()` method is blocknig and _server_ object is of the main scope.

So, how to make `run()` function non blocking?

**Comment by lganzzzo** [comment]
Related issues:
- https://github.com/oatpp/oatpp/issues/269

**Comment by bamkrs** [comment]
Just to bump this issue: `server.run()` accepts a bool which, if set to `true`, starts the server in its own thread.

https://github.com/oatpp/oatpp/blob/3cf5e8cab72d01c36e142f165117045f69f30903/src/oatpp/network/Server.hpp#L119

So `server.run()` is non-blocking. However, you will need to implement your own logic to keep the program running and when to call `server.stop()`.

**Comment by medenes** [comment]
Hi, @bamkrs 
Is somewhere a good example hot to handle logic in proper way?
I'm asking here because with 1.2.5 version there is the warning as below 
` W |2021-02-19 14:12:32 1613740352727296| [oatpp::network::server::run(bool)]:Using oatpp::network::server::run(bool) is deprecated and will be removed in the next release. Please implement your own threading.`
as we are using  `oatpp::network::server::run(true)`

**Comment by bamkrs** [comment]
Hey @medenes 
Leonid and me had some conversation about the feature/api and concluded that threading should be a responsibility of the "user". We both know that this is a highly requested task/feature. Give me a couple of hours, I'll prepare a proper example of how to do use the new APIs with threading. An easy and proper example long overdue.

**Comment by bamkrs** [comment]
I took a while longer because we wanted to create a whole bunch of examples that are both reviewed and quality-checked by @lganzzzo as well as me.

The new repository https://github.com/oatpp/oatpp-threaded-starter shows many configurations how to run Oat++ in its own thread. From simple No-Stop to Stop-Simple and ending in Oat++ completely isolated in its own thread-scope.

We recommend the Simple-Stop for most applications! You can find it here: https://github.com/oatpp/oatpp-threaded-starter/blob/master/src/App_StopSimple.cpp

The other examples are non trivial and highly specialized on specific environments or requirements. Please read the comments carefully and think about the consequences twice. If someone wants to use them please get back to us in an issue in the new repository and we can assist you with them. Again: These examples introduce special conditions and requirements for your code!

**Comment by medenes** [comment]
Thank you for effort :)
