### ISSUE TITLE
Retrieve result of CoroutineWithResult at call site from Executor

### ISSUE THREAD

**Issue by ktnr** [oatpp/oatpp#329]
Is it possible to access the result of an async call outside of coroutines (similar to synchronuous calls)? I would like to avoid putting application logic into coroutines. What is recommended as best practice here?

Specifically, with synchronuous calls, I can do
``` 
auto inputDto = InputDto::createShared()
auto oatppResponse = client->putRequest(inputDto);
auto responseDto = oatppResponse ->readBodyToDto<oatpp::Object<ResponseDto>>(objectMapper.get());
```
and have access to the response from the call site.

With async calls I would do [something like this](https://oatpp.io/docs/oatpp-coroutines/#call-coroutine-and-return-result) 
```
oatpp::async::Executor executor();

executor.execute<MyCoroutineWithResult>();
// I want access to the response DTO here. Is something like this possible?
// auto responseDto = executor.execute<MyCoroutineWithResult>();

executor.waitTasksFinished();
executor.stop();
executor.join();
```
but do not have access to the response at the call site because the client is called from within the coroutine.

I guess I could pass a `shared_ptr` to the constructor of the coroutine, similar to [this](https://oatpp.io/docs/oatpp-coroutines/#counter). But it seems like a workaround rather than a solution.

**Comment by lganzzzo** [comment]
Hello @ktnr ,

Please describe what you are trying to do in more detail.

Meanwhile here is some info you may find helpful:

- Example of how to do API calls using Async API: https://github.com/oatpp/example-api-client/blob/master/src/AsyncExample.hpp#L66
   You may use the `readBodyToDtoAsync` instead of `readBodyToStringAsync`.
- The top-most coroutine is always the one that extends `oatpp::async::Coroutine` NOT the `oatpp::async::CoroutineWithResult`.
-  To communicate some data back from the coroutine you pass a callback to the constructor of a coroutine (if it's really needed).
- Take a look at the complete example of asynchronous chat - https://github.com/lganzzzo/canchat - to better understand how to organize an async code.

The "best practice" here can be described something like the following:

- You have part "A" of the application running Simple API.
- You have part "B" of the application running Async API.
- Parts "A" and "B" have their own, independent from each other lifecycles.
- Parts "A" and "B" communicate with each other via callbacks and events.

Regards,
Leonid

**Comment by lganzzzo** [comment]
I'm closing this one.
@ktnr , please feel free to create a new one if you have more questions.
