### ISSUE TITLE
Request timeout and raw data

### ISSUE THREAD

**Issue by nikpx** [oatpp/oatpp#418]
Hello,

I was testing the HTTP server with the following Python script and I noticed the following:

1) If we send raw data (using the send/sendall), the server does not output/show a connection that was made. Would it be possible to somehow modify this and at least show that a new connection started?

2) I noticed that if the client waits for data (recv command in the script) then the server does not close the connection, even after 5 minutes. Is there an option to set a timeout value?

Thank you

import socket

```
host = "127.0.0.1"
port = 8000                   
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((host, port))
s.sendall(b'Hello, world')
data = s.recv(1024)
s.close()
```

**Comment by lganzzzo** [comment]
Hello @nikpx ,

> If we send raw data (using the send/sendall), the server does not output/show a connection that was made. Would it be possible to somehow modify this and at least show that a new connection started?

You can inherit `HttpConnectionHandler` and put logs in [handleConnection](https://github.com/oatpp/oatpp/blob/master/src/oatpp/web/server/HttpConnectionHandler.cpp#L63) method.

Also, if you are going to use your custom protocol instead of HTTP - then just implement your own `ConnectionHandler`.

> I noticed that if the client waits for data (recv command in the script) then the server does not close the connection, even after 5 minutes. Is there an option to set a timeout value?

By default, oatpp server will keep connections alive in order to reuse them.
However, if the connection is dead or is too slow then it will be possible to close such connections with the `ConnectionMonitor` starting from oatpp `1.3.0`.

See https://github.com/oatpp/oatpp/issues/284

**Comment by lganzzzo** [comment]
Now there is a ConnectionMonitor in `1.3.0` you can configure max TTL for an opened connection.
See [ConnectionMonitor](https://github.com/oatpp/oatpp/blob/master/changelog/1.3.0.md#connectionmonitor)
