### ISSUE TITLE
oatpp::utils::conversion::primitiveToStr

### ISSUE THREAD

**Issue by satarovbekzhan** [oatpp/oatpp#437]
Shuold the size of a value be 100? I think it would better to be equal to the length of a value + 1. Because in the case when I am trying to get oatpp::String from std::string, the length of a value could be much bigger than 100. Or there is another way for it?

```
oatpp::String primitiveToStr(T value, const char* pattern){
    v_char8 buff [**100**];
    auto size = primitiveToCharSequence(value, &buff[0], **100**, pattern);
    if(size > 0){
      return oatpp::String((const char*)&buff[0], size, true);
    }
    return nullptr;
  }
```

**Comment by bamkrs** [comment]
Hey @satarovbekzhan thanks for your question.
If you look closely to the intention of this function it's purpose is to convert **primitives** to an `oatpp::String`.
Primitives are pod's like `int`, `float` and so on. So 100bytes should be more than enough in this case. We chose performance over memory footprint in this regard because it's an very purpose build function only called in an well controlled context. Further, there are designated functions for converting `std::string` to `oatpp::String`. 
One method would be

```c++
// std::string foo;
oatpp::String bar(foo.c_str(), foo.length(), true);
```
