### ISSUE TITLE
Storing injected components by reference

### ISSUE THREAD

**Issue by ZizhengTai** [oatpp/oatpp#551]
Suppose I have registered a component of type `std::shared_ptr<FooService>` and have injected it into my `FooController`'s constructor with `OATPP_COMPONENT(std::shared_ptr<FooService>, fooService)`. My question is, is it safe to store simply a `FooService&` inside `FooController`, instead of a copy of the `std::shared_ptr<FooService>`?

I suppose the answer is yes, as the `std::shared_ptr<FooService>` is kept alive in the global environment until `oatpp::base::Environment::destroy()` is called. If this is true, as a follow up question, isn't it enough to register a `std::unique_ptr<FooService>` in the first place?

**Comment by lganzzzo** [comment]
Hello @ZizhengTai ,

Thanks for bringing up this topic.
The oatpp components are a bit confusing at the moment, and I want to change this a bit in `1.4.0`.

The way it's currently working right now:

```cpp
struct AppComponents {

  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, httpRouter)([] {
    return oatpp::web::server::HttpRouter::createShared();
  }());

};

  ...

{

 AppComponents components; //<-- all components are created and stored in the Env.

 /* declare variable std::shared_ptr<oatpp::web::server::HttpRouter>& httpRouter */
 OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, httpRouter); //<-- httpRouter is a reference to shared_ptr

} //<-- all components are deleted from Env and destroyed.
```

Note that components are destroyed and removed from Env when the component object is destroyed. And NOT on the `oatpp::base::Environment::destroy()`  call.

---

To my mind the current implementation has the following cons:
- `oatpp::base::Environment::Component<TYPE>` has no move-assignment operator - which prevents use of `std::unique_ptr`.
- `OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, httpRouter);` should NOT implicitly use reference. Instead user should be able to specify that 


---

Now answering the question:
- `OATPP_COMPONENT(std::shared_ptr<FooService>, fooService)` is already stored as a reference.
- `std::unique_ptr<FooService>` can't be used since `Environment::Component` has no move-assign operator.

**Comment by ZizhengTai** [comment]
Hi @lganzzzo, not sure I followed this part:
> OATPP_COMPONENT(std::shared_ptr<FooService>, fooService) is already stored as a reference.

My understanding is that a `std::shared_ptr<FooService>` is stored inside the component container (which is just a custom class), and my question (to which the answer I believe is yes) is whether it's OK to do the following:
```cpp
class FooController ... {
  FooController(
    // This gets expanded to `shared_ptr<FooService>& fooService = ...`
    OATPP_COMPONENT(shared_ptr<FooService>, fooService)
  ) : fooService(*fooService)
  {}

  // Note that here we store a plain reference instead of a `shared_ptr<FooService>`
  FooService& fooService;
};
```
I believe the `FooService& fooService;` part is OK since the instance is kept alive in the component container class. I'm just not sure whether Oat++ possibly expects the controller to copy the `shared_ptr` for some reason, and if I don't copy it bad things can happen.

**Comment by lganzzzo** [comment]
Yes, It should be safe to do unless you delete FooService component before FooController:)
Otherwise, I don't see any problems with this code.
