### ISSUE TITLE
disable a log priority after compiling

### ISSUE THREAD

**Issue by Augustus-demon** [oatpp/oatpp#567]
HI , just as title says, can we disable a specific log priority when using the library, perhaps a logger config or something?
In that way ,we don't need to compile oatpp again if we need to disable or enable a priority temporarily.

**Comment by bamkrs** [comment]
Hey @Augustus-demon 
Sure thing, you can enable/disable priorities on an per-category (if you are using log-categories: https://github.com/oatpp/oatpp/blob/306a01c1e2128859ff6fa8422c788eca43a1fb3c/src/oatpp/core/base/Environment.hpp#L192) level as well as global. 
The default logger supports dynamic priority toggling. However, it is a bit hidden because it's not advertised by the logging-interface. 
Let me edit this answer in a couple of minutes with some code.

**Comment by Augustus-demon** [comment]
Thanks.  you mean if I need to disable priority of my customized logger, my logger should rather inherit from # oatpp::base::DefaultLogger insted of # oatpp::base::Logger.

**Comment by bamkrs** [comment]
That's up to you. If you inherit from `oatpp::base::Logger` you have to come up with your own priority-system. If you inherit from `oatpp::base::DefaultLogger` you can reuse the given system and only override the actual log-function to fit your needs.

**Comment by Augustus-demon** [comment]
OK, I see.Thanks anyway. : )
