### ISSUE TITLE
MacOS builds failing to start on Azure-Pipelines.

### ISSUE THREAD

**Issue by lganzzzo** [oatpp/oatpp#66]
MAC builds failing with status - `Abandoned` on step initialize agent.

Hello @kaylangan,

I mentioned you because you wrote me before in the following issue: https://github.com/oatpp/oatpp/pull/17 .

> I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

Do I still can consult you regarding Azure Pipelines?
If yes - please let me know if you have any thoughts on this issue.

Failing build link - https://dev.azure.com/lganzzzo/lganzzzo/_build/results?buildId=1039

MacOS builds are temporary disabled in https://github.com/oatpp/oatpp/commit/c0a75af2b7d4c2727b5e5630407e46b02010f5b7

Thank you,
Leonid

**Comment by kaylangan** [comment]
@lganzzzo thanks for your patience. The issue should be mitigated. We had an outage in our West Europe region. The incident was mitigated around 8/8:30 AM EST. You can find more info here: https://status.dev.azure.com/_event/117874362 (note, it says the issue was "build delays" but it actually caused build failures).

**Comment by lganzzzo** [comment]
Hey @kaylangan ,
Thanks a lot for the info!

**Comment by lganzzzo** [comment]
Verified.
