### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by tfiner** [oatpp/oatpp#722]
In file: oatpp/core/macro/component.hpp

# Question

What I'm trying to do: make a plugin based executable that loads plugin libraries on demand.  The main application contains the Oat++ environment, and I want plugins be able to append their endpoints in the main application's controller.

The problem I am running into is that the DI framework is using static variables to map all the components in the Environment.  This highlights a common, subtle problem with using global state in libraries.  Static variables live in the global memory segment, and on windows, each DLL gets its own static address space.  That means objects registered in a plugin DLL is not seen by an executable with an Environment that lives in a different memory segment.  https://stackoverflow.com/a/19374253

What would make this way easier would be if the DI map was a member of the Environment and the registry functions made public. Then a pointer to the environment could be passed to a DLL to register its components in.  If a static environment is really needed (or merely convenient), the Environment could remain be a singleton, as long as it had facilities for adding / removing components and a way to set the current environment.

Another way to get around this is if Oat++ could be used without having to depend on the DI framework.  DI is nice, but the problems it introduces aren't worth limitations (on windows anyways) that it enforces.

**Comment by lganzzzo** [comment]
Hello @tfiner , 

Oat++ can be used without DI. 
However, I don’t think it’s a problem here.

In your case I would try do the following:
- since oatpp is living in the main app let it live in the main app with all the DI and fancy stuff
- Plugins instead should not use oatpp directly
- You have to provide your custom interface to register endpoint in your main app.
- Plugins will use that interface providing handler that will be called from the main app when an endpoint was hit

Regards,
Leonid

**Comment by tfiner** [comment]
Hello @lganzzzo ,

Never mind, I should have realized that Oat++ builds as a static library and DLL isn't supported (I just built it with Cmake as a DLL and there were no exports).  Thank you for your time.

Best,
Tim
