### ISSUE TITLE
Deserialize DTO Wrapper into Template Dto Type

### ISSUE THREAD

**Issue by ftbmynameis** [oatpp/oatpp#750]
HI,

I havent looked too much into the details of how the dto serialization and deserialization works, but its quite the work to get through all the macro magic. So I hope you don't mind me asking how the deserialization works.
More specifically: I can deserialize a payload into a DTWrapper using "readBodyToDto". However I would like to deserialize into my exact DTO type.
I.e. I for a DTO of type "MyExactDto" I can only deserialize into "MyExactDto::Wrapper" and I was hoping there would be a convinient way to deserialize into the raw dto type and get an object of that type.
The main reason being that for proper seperation of concerns a service used to implement the business logic that is handled within an oatpp controller should actually be independent of oatpp.

At the moment I am using a convert method and do it by hand but that of course is quite the boilerplate code and very error prone, especially for when you add new fields :/

Thanks for any advice on how and if that is solvable within oatpp.

EDIT: Okay I for some reason I did not realize among all the typedef and shared pointers that there is a "get()" overload within ObjectWrapper which works for exactly that.

**Comment by lganzzzo** [comment]
Hello @ftbmynameis ,

Every oatpp mapping-enabled type is basically a shared_ptr of that type plus a type info:

```cpp
template <class T, class Clazz = __class::Void>
  ...
  std::shared_ptr<T> m_ptr; //<--- pointer to object
  const Type* m_valueType;  //<--- type info
```

With primitives to get the object you just have to dereference the wrapper (oatpp allows you to easily convert between wrapper and bare object):

```cpp
oatpp::String a = "hello";
std::string b = a;  // implicit dereferencing
std::string c = *a; // explicit
```

With objects there is no easy way to convert between DTO and bare object because **you SHOLD NOT do this**:

```cpp
oatpp::Object<MyDto> myDto = MyDto::createShared();
MyDto copy = *myDto.get(); // It's possible to do so, but you SHOULD NOT do this.
```

**NOTE:**
If you choose to work with oatpp DTOs - then work with oatpp DTOs.
If you choose to work with bare objects - then DO NOT use DTOs.

### Good practice is one of the following:

- Use DTOs for APIs and for backend (recommended)
- Use DTOs for APIs and use bare cpp structs for backend - manually convert (field by field) from DTOs to structs.

### Bad practice

Create DTO and store DTO object without the proper wrapper:

```cpp
auto myDto = MyDto::createShared();

myCollection.add(*myDto.get()); //<-- NEVER DO THIS. It makes no sense.
```

Regards,
Leonid

**Comment by ftbmynameis** [comment]
Hello there,

thanks for that detailed reponse. What Ive been doing was then indeed bad pratice and should not be done. Thanks for clarifying that. We will need manual converters then.

Regards,
ftbmynameis

**Comment by ftbmynameis** [comment]
Thanks for that anwser! That clarifies a lot.
